// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;

namespace Steam4NET
{

	[StructLayout(LayoutKind.Sequential,Pack=4)]
	public class ISteamUGC008VTable
	{
		public IntPtr CreateQueryUserUGCRequest0;
		public IntPtr CreateQueryAllUGCRequest1;
		public IntPtr CreateQueryUGCDetailsRequest2;
		public IntPtr SendQueryUGCRequest3;
		public IntPtr GetQueryUGCResult4;
		public IntPtr GetQueryUGCPreviewURL5;
		public IntPtr GetQueryUGCMetadata6;
		public IntPtr GetQueryUGCChildren7;
		public IntPtr GetQueryUGCStatistic8;
		public IntPtr GetQueryUGCNumAdditionalPreviews9;
		public IntPtr GetQueryUGCAdditionalPreview10;
		public IntPtr GetQueryUGCNumKeyValueTags11;
		public IntPtr GetQueryUGCKeyValueTag12;
		public IntPtr ReleaseQueryUGCRequest13;
		public IntPtr AddRequiredTag14;
		public IntPtr AddExcludedTag15;
		public IntPtr SetReturnKeyValueTags16;
		public IntPtr SetReturnLongDescription17;
		public IntPtr SetReturnMetadata18;
		public IntPtr SetReturnChildren19;
		public IntPtr SetReturnAdditionalPreviews20;
		public IntPtr SetReturnTotalOnly21;
		public IntPtr SetLanguage22;
		public IntPtr SetAllowCachedResponse23;
		public IntPtr SetCloudFileNameFilter24;
		public IntPtr SetMatchAnyTag25;
		public IntPtr SetSearchText26;
		public IntPtr SetRankedByTrendDays27;
		public IntPtr AddRequiredKeyValueTag28;
		public IntPtr RequestUGCDetails29;
		public IntPtr CreateItem30;
		public IntPtr StartItemUpdate31;
		public IntPtr SetItemTitle32;
		public IntPtr SetItemDescription33;
		public IntPtr SetItemUpdateLanguage34;
		public IntPtr SetItemMetadata35;
		public IntPtr SetItemVisibility36;
		public IntPtr SetItemTags37;
		public IntPtr SetItemContent38;
		public IntPtr SetItemPreview39;
		public IntPtr RemoveItemKeyValueTags40;
		public IntPtr AddItemKeyValueTag41;
		public IntPtr AddItemPreviewFile42;
		public IntPtr AddItemPreviewVideo43;
		public IntPtr UpdateItemPreviewFile44;
		public IntPtr UpdateItemPreviewVideo45;
		public IntPtr RemoveItemPreview46;
		public IntPtr SubmitItemUpdate47;
		public IntPtr GetItemUpdateProgress48;
		public IntPtr SetUserItemVote49;
		public IntPtr GetUserItemVote50;
		public IntPtr AddItemToFavorites51;
		public IntPtr RemoveItemFromFavorites52;
		public IntPtr SubscribeItem53;
		public IntPtr UnsubscribeItem54;
		public IntPtr GetNumSubscribedItems55;
		public IntPtr GetSubscribedItems56;
		public IntPtr GetItemState57;
		public IntPtr GetItemInstallInfo58;
		public IntPtr GetItemDownloadInfo59;
		public IntPtr DownloadItem60;
		public IntPtr BInitWorkshopForGameServer61;
		public IntPtr SuspendDownloads62;
		public IntPtr StartPlaytimeTracking63;
		public IntPtr StopPlaytimeTracking64;
		public IntPtr StopPlaytimeTrackingForAllItems65;
		private IntPtr DTorISteamUGC00866;
	};
	
	public class ISteamUGC008 : InteropHelp.NativeWrapper<ISteamUGC008VTable>
	{
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeCreateQueryUserUGCRequestUEEEUUU( IntPtr thisptr, UInt32 unAccountID, EUserUGCList eListType, EUGCMatchingUGCType eMatchingUGCType, EUserUGCListSortOrder eSortOrder, UInt32 nCreatorAppID, UInt32 nConsumerAppID, UInt32 unPage );
		public UInt64 CreateQueryUserUGCRequest( UInt32 unAccountID, EUserUGCList eListType, EUGCMatchingUGCType eMatchingUGCType, EUserUGCListSortOrder eSortOrder, UInt32 nCreatorAppID, UInt32 nConsumerAppID, UInt32 unPage ) 
		{
			return this.GetFunction<NativeCreateQueryUserUGCRequestUEEEUUU>( this.Functions.CreateQueryUserUGCRequest0 )( this.ObjectAddress, unAccountID, eListType, eMatchingUGCType, eSortOrder, nCreatorAppID, nConsumerAppID, unPage ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeCreateQueryAllUGCRequestEEUUU( IntPtr thisptr, EUGCQuery eQueryType, EUGCMatchingUGCType eMatchingeMatchingUGCTypeFileType, UInt32 nCreatorAppID, UInt32 nConsumerAppID, UInt32 unPage );
		public UInt64 CreateQueryAllUGCRequest( EUGCQuery eQueryType, EUGCMatchingUGCType eMatchingeMatchingUGCTypeFileType, UInt32 nCreatorAppID, UInt32 nConsumerAppID, UInt32 unPage ) 
		{
			return this.GetFunction<NativeCreateQueryAllUGCRequestEEUUU>( this.Functions.CreateQueryAllUGCRequest1 )( this.ObjectAddress, eQueryType, eMatchingeMatchingUGCTypeFileType, nCreatorAppID, nConsumerAppID, unPage ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeCreateQueryUGCDetailsRequestUU( IntPtr thisptr, ref UInt64 arg0, UInt32 arg1 );
		public UInt64 CreateQueryUGCDetailsRequest( ref UInt64 arg0, UInt32 arg1 ) 
		{
			return this.GetFunction<NativeCreateQueryUGCDetailsRequestUU>( this.Functions.CreateQueryUGCDetailsRequest2 )( this.ObjectAddress, ref arg0, arg1 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeSendQueryUGCRequestU( IntPtr thisptr, UInt64 handle );
		public UInt64 SendQueryUGCRequest( UInt64 handle ) 
		{
			return this.GetFunction<NativeSendQueryUGCRequestU>( this.Functions.SendQueryUGCRequest3 )( this.ObjectAddress, handle ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetQueryUGCResultUUS( IntPtr thisptr, UInt64 handle, UInt32 index, ref SteamUGCDetails_t pDetails );
		public bool GetQueryUGCResult( UInt64 handle, UInt32 index, ref SteamUGCDetails_t pDetails ) 
		{
			return this.GetFunction<NativeGetQueryUGCResultUUS>( this.Functions.GetQueryUGCResult4 )( this.ObjectAddress, handle, index, ref pDetails ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetQueryUGCPreviewURLUUSU( IntPtr thisptr, UInt64 handle, UInt32 arg1, StringBuilder arg2, UInt32 arg3 );
		public bool GetQueryUGCPreviewURL( UInt64 handle, UInt32 arg1, StringBuilder arg2, UInt32 arg3 ) 
		{
			return this.GetFunction<NativeGetQueryUGCPreviewURLUUSU>( this.Functions.GetQueryUGCPreviewURL5 )( this.ObjectAddress, handle, arg1, arg2, arg3 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetQueryUGCMetadataUUSU( IntPtr thisptr, UInt64 handle, UInt32 arg1, StringBuilder arg2, UInt32 arg3 );
		public bool GetQueryUGCMetadata( UInt64 handle, UInt32 arg1, StringBuilder arg2, UInt32 arg3 ) 
		{
			return this.GetFunction<NativeGetQueryUGCMetadataUUSU>( this.Functions.GetQueryUGCMetadata6 )( this.ObjectAddress, handle, arg1, arg2, arg3 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetQueryUGCChildrenUUUU( IntPtr thisptr, UInt64 handle, UInt32 arg1, ref UInt64 arg2, UInt32 arg3 );
		public bool GetQueryUGCChildren( UInt64 handle, UInt32 arg1, ref UInt64 arg2, UInt32 arg3 ) 
		{
			return this.GetFunction<NativeGetQueryUGCChildrenUUUU>( this.Functions.GetQueryUGCChildren7 )( this.ObjectAddress, handle, arg1, ref arg2, arg3 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetQueryUGCStatisticUUEU( IntPtr thisptr, UInt64 handle, UInt32 arg1, EItemStatistic arg2, ref UInt32 arg3 );
		public bool GetQueryUGCStatistic( UInt64 handle, UInt32 arg1, EItemStatistic arg2, ref UInt32 arg3 ) 
		{
			return this.GetFunction<NativeGetQueryUGCStatisticUUEU>( this.Functions.GetQueryUGCStatistic8 )( this.ObjectAddress, handle, arg1, arg2, ref arg3 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeGetQueryUGCNumAdditionalPreviewsUU( IntPtr thisptr, UInt64 handle, UInt32 arg1 );
		public UInt32 GetQueryUGCNumAdditionalPreviews( UInt64 handle, UInt32 arg1 ) 
		{
			return this.GetFunction<NativeGetQueryUGCNumAdditionalPreviewsUU>( this.Functions.GetQueryUGCNumAdditionalPreviews9 )( this.ObjectAddress, handle, arg1 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetQueryUGCAdditionalPreviewUUUSUSUE( IntPtr thisptr, UInt64 handle, UInt32 arg1, UInt32 arg2, StringBuilder arg3, UInt32 arg4, StringBuilder arg5, UInt32 arg6, ref EItemPreviewType arg7 );
		public bool GetQueryUGCAdditionalPreview( UInt64 handle, UInt32 arg1, UInt32 arg2, StringBuilder arg3, UInt32 arg4, StringBuilder arg5, UInt32 arg6, ref EItemPreviewType arg7 ) 
		{
			return this.GetFunction<NativeGetQueryUGCAdditionalPreviewUUUSUSUE>( this.Functions.GetQueryUGCAdditionalPreview10 )( this.ObjectAddress, handle, arg1, arg2, arg3, arg4, arg5, arg6, ref arg7 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeGetQueryUGCNumKeyValueTagsUU( IntPtr thisptr, UInt64 handle, UInt32 arg1 );
		public UInt32 GetQueryUGCNumKeyValueTags( UInt64 handle, UInt32 arg1 ) 
		{
			return this.GetFunction<NativeGetQueryUGCNumKeyValueTagsUU>( this.Functions.GetQueryUGCNumKeyValueTags11 )( this.ObjectAddress, handle, arg1 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetQueryUGCKeyValueTagUUUSUSU( IntPtr thisptr, UInt64 handle, UInt32 arg1, UInt32 arg2, StringBuilder arg3, UInt32 arg4, StringBuilder arg5, UInt32 arg6 );
		public bool GetQueryUGCKeyValueTag( UInt64 handle, UInt32 arg1, UInt32 arg2, StringBuilder arg3, UInt32 arg4, StringBuilder arg5, UInt32 arg6 ) 
		{
			return this.GetFunction<NativeGetQueryUGCKeyValueTagUUUSUSU>( this.Functions.GetQueryUGCKeyValueTag12 )( this.ObjectAddress, handle, arg1, arg2, arg3, arg4, arg5, arg6 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeReleaseQueryUGCRequestU( IntPtr thisptr, UInt64 handle );
		public bool ReleaseQueryUGCRequest( UInt64 handle ) 
		{
			return this.GetFunction<NativeReleaseQueryUGCRequestU>( this.Functions.ReleaseQueryUGCRequest13 )( this.ObjectAddress, handle ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeAddRequiredTagUS( IntPtr thisptr, UInt64 handle, string pTagName );
		public bool AddRequiredTag( UInt64 handle, string pTagName ) 
		{
			return this.GetFunction<NativeAddRequiredTagUS>( this.Functions.AddRequiredTag14 )( this.ObjectAddress, handle, pTagName ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeAddExcludedTagUS( IntPtr thisptr, UInt64 handle, string pTagName );
		public bool AddExcludedTag( UInt64 handle, string pTagName ) 
		{
			return this.GetFunction<NativeAddExcludedTagUS>( this.Functions.AddExcludedTag15 )( this.ObjectAddress, handle, pTagName ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetReturnKeyValueTagsUB( IntPtr thisptr, UInt64 handle, [MarshalAs(UnmanagedType.I1)] bool arg1 );
		public bool SetReturnKeyValueTags( UInt64 handle, bool arg1 ) 
		{
			return this.GetFunction<NativeSetReturnKeyValueTagsUB>( this.Functions.SetReturnKeyValueTags16 )( this.ObjectAddress, handle, arg1 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetReturnLongDescriptionUB( IntPtr thisptr, UInt64 handle, [MarshalAs(UnmanagedType.I1)] bool bReturnLongDescription );
		public bool SetReturnLongDescription( UInt64 handle, bool bReturnLongDescription ) 
		{
			return this.GetFunction<NativeSetReturnLongDescriptionUB>( this.Functions.SetReturnLongDescription17 )( this.ObjectAddress, handle, bReturnLongDescription ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetReturnMetadataUB( IntPtr thisptr, UInt64 handle, [MarshalAs(UnmanagedType.I1)] bool arg1 );
		public bool SetReturnMetadata( UInt64 handle, bool arg1 ) 
		{
			return this.GetFunction<NativeSetReturnMetadataUB>( this.Functions.SetReturnMetadata18 )( this.ObjectAddress, handle, arg1 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetReturnChildrenUB( IntPtr thisptr, UInt64 handle, [MarshalAs(UnmanagedType.I1)] bool arg1 );
		public bool SetReturnChildren( UInt64 handle, bool arg1 ) 
		{
			return this.GetFunction<NativeSetReturnChildrenUB>( this.Functions.SetReturnChildren19 )( this.ObjectAddress, handle, arg1 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetReturnAdditionalPreviewsUB( IntPtr thisptr, UInt64 handle, [MarshalAs(UnmanagedType.I1)] bool arg1 );
		public bool SetReturnAdditionalPreviews( UInt64 handle, bool arg1 ) 
		{
			return this.GetFunction<NativeSetReturnAdditionalPreviewsUB>( this.Functions.SetReturnAdditionalPreviews20 )( this.ObjectAddress, handle, arg1 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetReturnTotalOnlyUB( IntPtr thisptr, UInt64 handle, [MarshalAs(UnmanagedType.I1)] bool bReturnTotalOnly );
		public bool SetReturnTotalOnly( UInt64 handle, bool bReturnTotalOnly ) 
		{
			return this.GetFunction<NativeSetReturnTotalOnlyUB>( this.Functions.SetReturnTotalOnly21 )( this.ObjectAddress, handle, bReturnTotalOnly ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetLanguageUS( IntPtr thisptr, UInt64 handle, string arg1 );
		public bool SetLanguage( UInt64 handle, string arg1 ) 
		{
			return this.GetFunction<NativeSetLanguageUS>( this.Functions.SetLanguage22 )( this.ObjectAddress, handle, arg1 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetAllowCachedResponseUU( IntPtr thisptr, UInt64 handle, UInt32 unMaxAgeSeconds );
		public bool SetAllowCachedResponse( UInt64 handle, UInt32 unMaxAgeSeconds ) 
		{
			return this.GetFunction<NativeSetAllowCachedResponseUU>( this.Functions.SetAllowCachedResponse23 )( this.ObjectAddress, handle, unMaxAgeSeconds ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetCloudFileNameFilterUS( IntPtr thisptr, UInt64 handle, string pMatchCloudFileName );
		public bool SetCloudFileNameFilter( UInt64 handle, string pMatchCloudFileName ) 
		{
			return this.GetFunction<NativeSetCloudFileNameFilterUS>( this.Functions.SetCloudFileNameFilter24 )( this.ObjectAddress, handle, pMatchCloudFileName ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetMatchAnyTagUB( IntPtr thisptr, UInt64 handle, [MarshalAs(UnmanagedType.I1)] bool bMatchAnyTag );
		public bool SetMatchAnyTag( UInt64 handle, bool bMatchAnyTag ) 
		{
			return this.GetFunction<NativeSetMatchAnyTagUB>( this.Functions.SetMatchAnyTag25 )( this.ObjectAddress, handle, bMatchAnyTag ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetSearchTextUS( IntPtr thisptr, UInt64 handle, string pSearchText );
		public bool SetSearchText( UInt64 handle, string pSearchText ) 
		{
			return this.GetFunction<NativeSetSearchTextUS>( this.Functions.SetSearchText26 )( this.ObjectAddress, handle, pSearchText ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetRankedByTrendDaysUU( IntPtr thisptr, UInt64 handle, UInt32 unDays );
		public bool SetRankedByTrendDays( UInt64 handle, UInt32 unDays ) 
		{
			return this.GetFunction<NativeSetRankedByTrendDaysUU>( this.Functions.SetRankedByTrendDays27 )( this.ObjectAddress, handle, unDays ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeAddRequiredKeyValueTagUSS( IntPtr thisptr, UInt64 handle, string arg1, string arg2 );
		public bool AddRequiredKeyValueTag( UInt64 handle, string arg1, string arg2 ) 
		{
			return this.GetFunction<NativeAddRequiredKeyValueTagUSS>( this.Functions.AddRequiredKeyValueTag28 )( this.ObjectAddress, handle, arg1, arg2 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeRequestUGCDetailsUU( IntPtr thisptr, UInt64 nPublishedFileID, UInt32 unMaxAgeSeconds );
		public UInt64 RequestUGCDetails( UInt64 nPublishedFileID, UInt32 unMaxAgeSeconds ) 
		{
			return this.GetFunction<NativeRequestUGCDetailsUU>( this.Functions.RequestUGCDetails29 )( this.ObjectAddress, nPublishedFileID, unMaxAgeSeconds ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeCreateItemUE( IntPtr thisptr, UInt32 nConsumerAppId, EWorkshopFileType eFileType );
		public UInt64 CreateItem( UInt32 nConsumerAppId, EWorkshopFileType eFileType ) 
		{
			return this.GetFunction<NativeCreateItemUE>( this.Functions.CreateItem30 )( this.ObjectAddress, nConsumerAppId, eFileType ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeStartItemUpdateUU( IntPtr thisptr, UInt32 nConsumerAppId, UInt64 nPublishedFileID );
		public UInt64 StartItemUpdate( UInt32 nConsumerAppId, UInt64 nPublishedFileID ) 
		{
			return this.GetFunction<NativeStartItemUpdateUU>( this.Functions.StartItemUpdate31 )( this.ObjectAddress, nConsumerAppId, nPublishedFileID ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetItemTitleUS( IntPtr thisptr, UInt64 handle, string pchTitle );
		public bool SetItemTitle( UInt64 handle, string pchTitle ) 
		{
			return this.GetFunction<NativeSetItemTitleUS>( this.Functions.SetItemTitle32 )( this.ObjectAddress, handle, pchTitle ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetItemDescriptionUS( IntPtr thisptr, UInt64 handle, string pchDescription );
		public bool SetItemDescription( UInt64 handle, string pchDescription ) 
		{
			return this.GetFunction<NativeSetItemDescriptionUS>( this.Functions.SetItemDescription33 )( this.ObjectAddress, handle, pchDescription ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetItemUpdateLanguageUS( IntPtr thisptr, UInt64 handle, string arg1 );
		public bool SetItemUpdateLanguage( UInt64 handle, string arg1 ) 
		{
			return this.GetFunction<NativeSetItemUpdateLanguageUS>( this.Functions.SetItemUpdateLanguage34 )( this.ObjectAddress, handle, arg1 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetItemMetadataUS( IntPtr thisptr, UInt64 handle, string arg1 );
		public bool SetItemMetadata( UInt64 handle, string arg1 ) 
		{
			return this.GetFunction<NativeSetItemMetadataUS>( this.Functions.SetItemMetadata35 )( this.ObjectAddress, handle, arg1 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetItemVisibilityUE( IntPtr thisptr, UInt64 handle, ERemoteStoragePublishedFileVisibility eVisibility );
		public bool SetItemVisibility( UInt64 handle, ERemoteStoragePublishedFileVisibility eVisibility ) 
		{
			return this.GetFunction<NativeSetItemVisibilityUE>( this.Functions.SetItemVisibility36 )( this.ObjectAddress, handle, eVisibility ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetItemTagsUS( IntPtr thisptr, UInt64 updateHandle, ref SteamParamStringArray_t pTags );
		public bool SetItemTags( UInt64 updateHandle, ref SteamParamStringArray_t pTags ) 
		{
			return this.GetFunction<NativeSetItemTagsUS>( this.Functions.SetItemTags37 )( this.ObjectAddress, updateHandle, ref pTags ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetItemContentUS( IntPtr thisptr, UInt64 handle, string pszContentFolder );
		public bool SetItemContent( UInt64 handle, string pszContentFolder ) 
		{
			return this.GetFunction<NativeSetItemContentUS>( this.Functions.SetItemContent38 )( this.ObjectAddress, handle, pszContentFolder ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetItemPreviewUS( IntPtr thisptr, UInt64 handle, string pszPreviewFile );
		public bool SetItemPreview( UInt64 handle, string pszPreviewFile ) 
		{
			return this.GetFunction<NativeSetItemPreviewUS>( this.Functions.SetItemPreview39 )( this.ObjectAddress, handle, pszPreviewFile ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeRemoveItemKeyValueTagsUS( IntPtr thisptr, UInt64 handle, string arg1 );
		public bool RemoveItemKeyValueTags( UInt64 handle, string arg1 ) 
		{
			return this.GetFunction<NativeRemoveItemKeyValueTagsUS>( this.Functions.RemoveItemKeyValueTags40 )( this.ObjectAddress, handle, arg1 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeAddItemKeyValueTagUSS( IntPtr thisptr, UInt64 handle, string arg1, string arg2 );
		public bool AddItemKeyValueTag( UInt64 handle, string arg1, string arg2 ) 
		{
			return this.GetFunction<NativeAddItemKeyValueTagUSS>( this.Functions.AddItemKeyValueTag41 )( this.ObjectAddress, handle, arg1, arg2 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeAddItemPreviewFileUSE( IntPtr thisptr, UInt64 handle, string arg1, EItemPreviewType arg2 );
		public bool AddItemPreviewFile( UInt64 handle, string arg1, EItemPreviewType arg2 ) 
		{
			return this.GetFunction<NativeAddItemPreviewFileUSE>( this.Functions.AddItemPreviewFile42 )( this.ObjectAddress, handle, arg1, arg2 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeAddItemPreviewVideoUS( IntPtr thisptr, UInt64 handle, string arg1 );
		public bool AddItemPreviewVideo( UInt64 handle, string arg1 ) 
		{
			return this.GetFunction<NativeAddItemPreviewVideoUS>( this.Functions.AddItemPreviewVideo43 )( this.ObjectAddress, handle, arg1 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeUpdateItemPreviewFileUUS( IntPtr thisptr, UInt64 handle, UInt32 arg1, string arg2 );
		public bool UpdateItemPreviewFile( UInt64 handle, UInt32 arg1, string arg2 ) 
		{
			return this.GetFunction<NativeUpdateItemPreviewFileUUS>( this.Functions.UpdateItemPreviewFile44 )( this.ObjectAddress, handle, arg1, arg2 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeUpdateItemPreviewVideoUUS( IntPtr thisptr, UInt64 handle, UInt32 arg1, string arg2 );
		public bool UpdateItemPreviewVideo( UInt64 handle, UInt32 arg1, string arg2 ) 
		{
			return this.GetFunction<NativeUpdateItemPreviewVideoUUS>( this.Functions.UpdateItemPreviewVideo45 )( this.ObjectAddress, handle, arg1, arg2 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeRemoveItemPreviewUU( IntPtr thisptr, UInt64 handle, UInt32 arg1 );
		public bool RemoveItemPreview( UInt64 handle, UInt32 arg1 ) 
		{
			return this.GetFunction<NativeRemoveItemPreviewUU>( this.Functions.RemoveItemPreview46 )( this.ObjectAddress, handle, arg1 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeSubmitItemUpdateUS( IntPtr thisptr, UInt64 handle, string pchChangeNote );
		public UInt64 SubmitItemUpdate( UInt64 handle, string pchChangeNote ) 
		{
			return this.GetFunction<NativeSubmitItemUpdateUS>( this.Functions.SubmitItemUpdate47 )( this.ObjectAddress, handle, pchChangeNote ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate EItemUpdateStatus NativeGetItemUpdateProgressUUU( IntPtr thisptr, UInt64 handle, ref UInt64 punBytesProcessed, ref UInt64 punBytesTotal );
		public EItemUpdateStatus GetItemUpdateProgress( UInt64 handle, ref UInt64 punBytesProcessed, ref UInt64 punBytesTotal ) 
		{
			return this.GetFunction<NativeGetItemUpdateProgressUUU>( this.Functions.GetItemUpdateProgress48 )( this.ObjectAddress, handle, ref punBytesProcessed, ref punBytesTotal ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeSetUserItemVoteUB( IntPtr thisptr, UInt64 arg0, [MarshalAs(UnmanagedType.I1)] bool arg1 );
		public UInt64 SetUserItemVote( UInt64 arg0, bool arg1 ) 
		{
			return this.GetFunction<NativeSetUserItemVoteUB>( this.Functions.SetUserItemVote49 )( this.ObjectAddress, arg0, arg1 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeGetUserItemVoteU( IntPtr thisptr, UInt64 arg0 );
		public UInt64 GetUserItemVote( UInt64 arg0 ) 
		{
			return this.GetFunction<NativeGetUserItemVoteU>( this.Functions.GetUserItemVote50 )( this.ObjectAddress, arg0 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeAddItemToFavoritesUU( IntPtr thisptr, UInt32 arg0, UInt64 arg1 );
		public UInt64 AddItemToFavorites( UInt32 arg0, UInt64 arg1 ) 
		{
			return this.GetFunction<NativeAddItemToFavoritesUU>( this.Functions.AddItemToFavorites51 )( this.ObjectAddress, arg0, arg1 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeRemoveItemFromFavoritesUU( IntPtr thisptr, UInt32 arg0, UInt64 arg1 );
		public UInt64 RemoveItemFromFavorites( UInt32 arg0, UInt64 arg1 ) 
		{
			return this.GetFunction<NativeRemoveItemFromFavoritesUU>( this.Functions.RemoveItemFromFavorites52 )( this.ObjectAddress, arg0, arg1 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeSubscribeItemU( IntPtr thisptr, UInt64 nPublishedFileID );
		public UInt64 SubscribeItem( UInt64 nPublishedFileID ) 
		{
			return this.GetFunction<NativeSubscribeItemU>( this.Functions.SubscribeItem53 )( this.ObjectAddress, nPublishedFileID ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeUnsubscribeItemU( IntPtr thisptr, UInt64 nPublishedFileID );
		public UInt64 UnsubscribeItem( UInt64 nPublishedFileID ) 
		{
			return this.GetFunction<NativeUnsubscribeItemU>( this.Functions.UnsubscribeItem54 )( this.ObjectAddress, nPublishedFileID ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeGetNumSubscribedItems( IntPtr thisptr );
		public UInt32 GetNumSubscribedItems(  ) 
		{
			return this.GetFunction<NativeGetNumSubscribedItems>( this.Functions.GetNumSubscribedItems55 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeGetSubscribedItemsUU( IntPtr thisptr, ref UInt64 pvecPublishedFileID, UInt32 cMaxEntries );
		public UInt32 GetSubscribedItems( ref UInt64 pvecPublishedFileID, UInt32 cMaxEntries ) 
		{
			return this.GetFunction<NativeGetSubscribedItemsUU>( this.Functions.GetSubscribedItems56 )( this.ObjectAddress, ref pvecPublishedFileID, cMaxEntries ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeGetItemStateU( IntPtr thisptr, UInt64 arg0 );
		public UInt32 GetItemState( UInt64 arg0 ) 
		{
			return this.GetFunction<NativeGetItemStateU>( this.Functions.GetItemState57 )( this.ObjectAddress, arg0 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetItemInstallInfoUUSUB( IntPtr thisptr, UInt64 nPublishedFileID, ref UInt64 punSizeOnDisk, StringBuilder pchFolder, UInt32 cchFolderSize, ref bool pbLegacyItem );
		public bool GetItemInstallInfo( UInt64 nPublishedFileID, ref UInt64 punSizeOnDisk, StringBuilder pchFolder, ref bool pbLegacyItem ) 
		{
			return this.GetFunction<NativeGetItemInstallInfoUUSUB>( this.Functions.GetItemInstallInfo58 )( this.ObjectAddress, nPublishedFileID, ref punSizeOnDisk, pchFolder, (UInt32) pchFolder.Capacity, ref pbLegacyItem ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetItemDownloadInfoUUU( IntPtr thisptr, UInt64 arg0, ref UInt64 arg1, ref UInt64 arg2 );
		public bool GetItemDownloadInfo( UInt64 arg0, ref UInt64 arg1, ref UInt64 arg2 ) 
		{
			return this.GetFunction<NativeGetItemDownloadInfoUUU>( this.Functions.GetItemDownloadInfo59 )( this.ObjectAddress, arg0, ref arg1, ref arg2 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeDownloadItemUB( IntPtr thisptr, UInt64 arg0, [MarshalAs(UnmanagedType.I1)] bool arg1 );
		public bool DownloadItem( UInt64 arg0, bool arg1 ) 
		{
			return this.GetFunction<NativeDownloadItemUB>( this.Functions.DownloadItem60 )( this.ObjectAddress, arg0, arg1 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBInitWorkshopForGameServerUS( IntPtr thisptr, UInt32 arg0, string arg1 );
		public bool BInitWorkshopForGameServer( UInt32 arg0, string arg1 ) 
		{
			return this.GetFunction<NativeBInitWorkshopForGameServerUS>( this.Functions.BInitWorkshopForGameServer61 )( this.ObjectAddress, arg0, arg1 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeSuspendDownloadsB( IntPtr thisptr, [MarshalAs(UnmanagedType.I1)] bool arg0 );
		public void SuspendDownloads( bool arg0 ) 
		{
			this.GetFunction<NativeSuspendDownloadsB>( this.Functions.SuspendDownloads62 )( this.ObjectAddress, arg0 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeStartPlaytimeTrackingUU( IntPtr thisptr, ref UInt64 ullUnk, UInt32 uUnk );
		public Int32 StartPlaytimeTracking( ref UInt64 ullUnk, UInt32 uUnk ) 
		{
			return this.GetFunction<NativeStartPlaytimeTrackingUU>( this.Functions.StartPlaytimeTracking63 )( this.ObjectAddress, ref ullUnk, uUnk ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeStopPlaytimeTrackingUU( IntPtr thisptr, ref UInt64 ullUnk, UInt32 uUnk );
		public Int32 StopPlaytimeTracking( ref UInt64 ullUnk, UInt32 uUnk ) 
		{
			return this.GetFunction<NativeStopPlaytimeTrackingUU>( this.Functions.StopPlaytimeTracking64 )( this.ObjectAddress, ref ullUnk, uUnk ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeStopPlaytimeTrackingForAllItems( IntPtr thisptr );
		public Int32 StopPlaytimeTrackingForAllItems(  ) 
		{
			return this.GetFunction<NativeStopPlaytimeTrackingForAllItems>( this.Functions.StopPlaytimeTrackingForAllItems65 )( this.ObjectAddress ); 
		}
		
	};
}
